# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{- site.title -}}, {{- site.email -}}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{- site.myvariable -}}.
title: 도솔산화암사 
title-abbreviated: 마음은 자유롭게, 세상은 아름답게
email: dosol-hwaam@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  이 곳 도솔산화암사 도량을 세움은 고통을 여의고 즐거움을 나누며 부처를 이루기 위함이니 선남자 연여인 모두 와서 합장하고 절을 하오.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dosolhwaamsa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  dosolhwaamsa

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-paginate-v2
  # - sanitize
safe: false
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, test_suite, node_modules, _sites]

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: true # Show image or title text

collections:
  0_temple:
    output: true
  1_religious_part:
    output: true
  2_dosolnoin_part:
    output: true  
  3_volunteers_part:  
    output: true
  # application-guidelines:
  #   output: true
  # who-we-are:
  #   output: true
  # products-and-services:
  #   output: true

# Resource Room and Pagination
resources_name: "resource_room"
paginate: 16


# defaults:
#   -
#     scope:
#       path: "photography"
#     values:
#       permalink: /:path/:basename:output_ext

# Site configuration for Isomer Pages
##################################

# Homepage sections
# homepage_hero_i_want_to: true # if i_want_to is true, there will be no key highlights
homepage_careers: true
homepage_resources: true
homepage_programmes: false

# Custom CSS file path
# custom_css_path: "/misc/custom.css"
custom_css_path: "/do-not-touch/theme-colors/custom.css"
custom_print_css_path: "/assets/css/print.css"

# Isomer recommender system - only works for simple-page, leftnav-page, and post
recommender: true

# ############################################################
# # Site configuration for the Jekyll 3 Pagination Gem
# # The values here represent the defaults if nothing is set
pagination:
  
#   # Site-wide kill switch, disabled here it doesn't run at all 
  # enabled: true

#   # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

#   # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 12

#   # The permalink structure for the paginated pages (this can be any level deep)
#   permalink: ':num.html' # Pages are index.html inside this folder (default)
#   #permalink: '/page/:num.html' # Pages are simple html files 
#   #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

#  # Optional,omit or set both before and after to zero to disable. 
#  # Controls how the pagination trail for the paginated pages look like. 
#   trail: 
#     before: 2
#     after: 2

#   # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
#   sort_field: 'date'

#   # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
#   sort_reverse: true

# ############################################################

# autopages:
#   enabled: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
